
/* Crear rankings */
INSERT INTO ufc.ranking VALUES (1, "Flyweight ", 125);
INSERT INTO ufc.ranking VALUES (2, "Bantamweight", 135);
INSERT INTO ufc.ranking VALUES (3, "Featherweight", 145);
INSERT INTO ufc.ranking VALUES (4, "Lightweight", 155);
INSERT INTO ufc.ranking VALUES (5, "Welterweight", 170);
INSERT INTO ufc.ranking VALUES (6, "Middleweight", 185);
INSERT INTO ufc.ranking VALUES (7, "Light heavyweight", 205);
INSERT INTO ufc.ranking VALUES (8, "Heavyweight", 265);

/* Peleadores de Flyweight */
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo, fighter_full_photo) VALUES (1, "Alexandre", "THE CANNIBAL", "Pantoja", 125, 65, "1990-05-16", 33, 67, 36.5, "RIO DE JANEIRO, BRASIL", 26, 5, 0, "26-5-0", "1", "0", "THE_CANNIBAL_Pantoja_photo.png", "THE_CANNIBAL_Pantoja_photo_body.png");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (2, "Brandon", "THE ASSASSIN BABY", "Moreno", 125, 67, "1993-12-07", 29, 70, 38, "TIJUANA, MÉXICO", 21, 7, 2, "21-7-2", "1", "1", "THE_ASSASSIN_BABY_Moreno_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (3, "Deiveson", "DEUS DA GUERRA", "Figueiredo", 125, 65, "1987-12-18", 35, 68, 38, "SOURE, BRASIL", 21, 3, 1, "21-3-1", "1", "2", "DEUS_DA_GUERRA_Figueiredo_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (4, "Amir", "THE PRINCE", "Albazi", 125, 65, "1993-09-27", 29, 68, 38, "BAGHDAD, IRAK", 17, 1, 0, "17-1-0", "1", "3", "THE_PRINCE_Albazi_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (5, "Brandon", "RAW DAWG", "Royval", 125, 69, "1992-08-06", 30, 68, 38.5, "DENVER, ESTADOS UNIDOS", 15, 6, 0, "15-6-0", "1", "4", "RAW_DAWG_Royval_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (6, "Kai Kara-France", "DON'T BLINK", "", 125, 64, "1993-03-26", 30, 69, 37, "AUCKLAND, NUEVA ZELANDA", 24, 11, 0, "24-11-0", "1", "5", "DON'T_BLINK_Kai_Kara-France_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (7, "John", "THE MAULER", "Doe", 125, 76, "1990-09-21", 32, 80, 40, "NEW YORK, USA", 20, 5, 1, "20-5-1", "1", "6", "THE_MAULER_Doe_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (8, "Jane", "IRON LADY", "Smith", 125, 68, "1988-06-15", 35, 67, 36, "LOS ANGELES, USA", 18, 4, 0, "18-4-0", "1", "7", "IRON_LADY_Smith_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (9, "Mike", "THE STRIKER", "Johnson", 125, 72, "1995-02-10", 28, 75, 39, "LAS VEGAS, USA", 15, 3, 2, "15-3-2", "1", "8", "THE_STRIKER_Johnson_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (10, "Joseph", "JOE B", "Benavidez", 125, 65, "1984-07-31", 39, 65, 34, "SAN ANTONIO, USA", 28, 7, 0, "28-7-0", "1", "9", "JOE_B_Benavidez_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (11, "Askar", "BULLET", "Askarov", 125, 66, "1992-10-09", 30, 67, 35, "MACHACHKALA, RUSSIA", 15, 0, 1, "15-0-1", "1", "10", "BULLET_Askarov_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (12, "Alexis", "DA EXPLOSIVE", "Aragon", 125, 65, "1994-03-20", 29, 68, 35, "LOS ANGELES, USA", 12, 2, 0, "12-2-0", "1", "11", "DA_EXPLOSIVE_Aragon_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (13, "Matheus", "TIGRÃO", "Nicolau", 125, 65, "1987-06-02", 36, 67, 35, "BELO HORIZONTE, BRAZIL", 16, 2, 1, "16-2-1", "1", "12", "TIGRÃO_Nicolau_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (14, "Rogerio", "LITTLE FROG", "Bontorin", 125, 66, "1992-02-01", 31, 67, 35, "RIO DE JANEIRO, BRAZIL", 18, 3, 0, "18-3-0", "1", "13", "LITTLE_FROG_Bontorin_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (15, "David", "TORNADO", "Dvorak", 125, 66, "1993-08-13", 28, 68, 36, "PARDUBICE, CZECH REPUBLIC", 20, 3, 0, "20-3-0", "1", "14", "TORNADO_Dvorak_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (16, "Ryan", "BABY FACE", "Benoit", 125, 67, "1989-09-25", 33, 69, 36, "DALLAS, USA", 10, 7, 0, "10-7-0", "1", "15", "BABY_FACE_Benoit_photo");

/* Peleadores de Bantamweight */
INSERT INTO UFC.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (17, "Sean", "SUGAR", "O'Malley", 135, 71, "1994-09-24", 28, 72, 40, "HELENA, ESTADOS UNIDOS", 17, 1, 0, "17-1-0", "2", "0", "SUGAR_O'Malley_photo.png");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (18, "Aljamain", "FUNK MASTER", "Sterling", 125, 67, "1989-07-31", 34, 71, 39, "ESTADOS UNIDOS", 23, 4, 0, "23-4-0", "2", "1", "FUNK_MASTER_Sterling_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (19, "Merab", "THE MACHINE", "Dvalishvili", 125, 66, "1991-01-10", 32, 68, 38, "TBILISI, GEORGIA", 16, 4, 0, "16-4-0", "2", "2", "THE_MACHINE_Dvalishvili_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (20, "Petr", "NO MERCY", "Yan", 135, 67, "1993-02-11", 28, 67, 35, "OMSK, RUSSIA", 15, 2, 0, "15-2-0", "2", "3", "NO_MERCY_Yan_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (21, "Cory", "SANDMAN", "Sandhagen", 135, 68, "1992-04-20", 29, 70, 35, "AURORA, USA", 16, 3, 0, "16-3-0", "2", "4", "SANDMAN_Sandhagen_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (22, "TJ", "KILLASHAW", "Dillashaw", 135, 67, "1986-02-07", 37, 68, 34, "SONORA, USA", 16, 4, 0, "16-4-0", "2", "5", "KILLASHAW_Dillashaw_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (23, "Jose", "SHORTY", "Torres", 135, 65, "1992-01-07", 29, 67, 34, "CHICAGO, USA", 10, 2, 0, "10-2-0", "2", "6", "SHORTY_Torres_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (24, "Marlon", "MAGIC", "Moraes", 135, 68, "1988-04-26", 33, 67, 34, "NOVA FRIBURGO, BRAZIL", 23, 8, 1, "23-8-1", "2", "7", "MAGIC_Moraes_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (25, "Pedro", "THE YOUNG PUNISHER", "Munhoz", 135, 66, "1986-09-24", 35, 67, 35, "SAO PAULO, BRAZIL", 19, 6, 0, "19-6-0", "2", "8", "THE_YOUNG_PUNISHER_Munhoz_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (26, "Raphael", "STINGER", "Assuncao", 135, 66, "1982-07-19", 39, 66, 34, "RECIFE, BRAZIL", 27, 7, 0, "27-7-0", "2", "9", "STINGER_Assuncao_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (27, "Cody", "NO LOVE", "Garbrandt", 135, 68, "1991-07-07", 32, 68, 34, "CLEVELAND, USA", 12, 3, 0, "12-3-0", "2", "10", "NO_LOVE_Garbrandt_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (28, "Ricky", "EL GALLERO", "Simon", 135, 66, "1992-05-29", 31, 67, 34, "TACOMA, USA", 17, 3, 0, "17-3-0", "2", "11", "EL_GALLERO_Simon_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (29, "Rani", "EL TAPATIO", "Yahya", 135, 67, "1984-12-12", 37, 67, 35, "Sao Paulo, Brazil", 27, 10, 0, "27-10-0", "2", "12", "EL_TAPATIO_Yahya_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (30, "Casey", "SIX GUN", "Kenney", 135, 68, "1991-08-20", 32, 68, 34, "TUCSON, USA", 18, 3, 1, "18-3-1", "2", "13", "SIX_GUN_Kenney_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (31, "Adrian", "THE BULL", "Yanez", 135, 67, "1994-07-29", 27, 68, 34, "HOUSTON, USA", 15, 3, 0, "15-3-0", "2", "14", "THE_BULL_Yanez_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (32, "Nate", "THE NATURAL", "Diaz", 170, 72, "1985-04-16", 36, 76, 38, "STOCKTON, USA", 21, 13, 0, "21-13-0", "2", "15", "THE_NATURAL_Diaz_photo");

/* Peleadores de Featherweight */
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (33, "Alexander", "THE GREAT", "Volkanovski", 145, 66, "1988-09-29", 34, 71, 36, "SHELLHARBOUR, AUSTRALIA", 26, 2, 0, "26-2-0", "3", "0", "THE_GREAT_Volk_photo.png");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (34, "Brian", "T-CITY", "Ortega", 145, 70, "1991-02-21", 32, 70, 34, "LOS ANGELES, USA", 15, 1, 0, "15-1-0", "3", "1", "T-CITY_Ortega_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (35, "Calvin", "THE BOSTON FINISHER", "Kattar", 145, 71, "1988-03-26", 33, 72, 36, "METHUEN, USA", 22, 5, 0, "22-5-0", "3", "2", "THE_BOSTON_FINISHER_Kattar_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (36, "Josh", "THE GENTLEMAN", "Emmett", 145, 68, "1985-12-07", 37, 70, 36, "SACRAMENTO, USA", 16, 3, 0, "16-3-0", "3", "3", "THE_GENTLEMAN_Emmett_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (37, "Edson", "JUNIOR", "Barboza", 145, 70, "1986-01-21", 37, 75, 39, "RIO DE JANEIRO, BRAZIL", 21, 9, 0, "21-9-0", "3", "4", "JUNIOR_Barboza_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (38, "Yair", "EL PANTERA", "Rodriguez", 145, 71, "1992-10-06", 30, 71, 35, "CHIHUAHUA, MEXICO", 13, 2, 0, "13-2-0", "3", "5", "EL_PANTERA_Rodriguez_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (39, "Jeremy", "LIL' HEATHEN", "Stephens", 145, 68, "1986-05-26", 36, 71, 35, "DES MOINES, USA", 28, 18, 0, "28-18-0", "3", "6", "LIL_HEATHEN_Stephens_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (40, "Arnold", "ALMIGHTY", "Allen", 145, 71, "1994-01-21", 27, 73, 37, "SILSDEN, UNITED KINGDOM", 18, 1, 0, "18-1-0", "3", "7", "ALMIGHTY_Allen_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (41, "Shane", "HURRICANE", "Burgos", 145, 69, "1990-10-20", 31, 75, 38, "WOODBURY, USA", 14, 3, 0, "14-3-0", "3", "8", "HURRICANE_Burgos_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (42, "Ryan", "SUPREME", "Hall", 145, 73, "1985-10-02", 36, 76, 38, "BIRMINGHAM, UNITED KINGDOM", 10, 9, 0, "10-9-0", "3", "9", "SUPREME_Hall_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (43, "Andre", "TOUCHY", "Fili", 145, 71, "1990-06-25", 31, 73, 36, "SACRAMENTO, USA", 22, 9, 0, "22-9-0", "3", "10", "TOUCHY_Fili_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (44, "Sodiq", "SUPER", "Yusuff", 145, 69, "1993-05-19", 28, 72, 37, "LAGOS, NIGERIA", 11, 1, 0, "11-1-0", "3", "11", "SUPER_Yusuff_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (45, "Shane", "THE HURRICANE", "Young", 145, 70, "1993-03-31", 28, 72, 36, "MCKEESPORT, USA", 15, 5, 0, "15-5-0", "3", "12", "THE_HURRICANE_Young_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (46, "Movsar", "BLACK WOLFF", "Evloev", 145, 68, "1994-09-11", 27, 70, 36, "GROZNY, RUSSIA", 15, 0, 0, "15-0-0", "3", "13", "BLACK_WOLFF_Evloev_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (47, "Lerone", "THE PRODIGY", "Murphy", 145, 72, "1987-09-26", 35, 75, 38, "PHILADELPHIA, USA", 12, 4, 0, "12-4-0", "3", "14", "THE_PRODIGY_Murphy_photo");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number, fighter_photo) VALUES (48, "Austin", "THUD", "Lingo", 145, 71, "1995-10-31", 27, 74, 38, "SACRAMENTO, USA", 9, 1, 0, "9-1-0", "3", "15", "THUD_Lingo_photo");

/* Peleadores de Lightweight */
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (49, "Charles", "DO BRONX", "Oliveira", 155, 71, "1989-10-17", 32, 74, 38, "GUARUJA, BRAZIL", 30, 8, 0, "30-8-0", "4", "0");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (50, "Justin", "THE HIGHLIGHT", "Gaethje", 155, 71, "1988-11-14", 33, 70, 36, "Safford, USA", 22, 3, 0, "22-3-0", "4", "1");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (51, "Dustin", "THE DIAMOND", "Poirier", 155, 69, "1989-01-19", 32, 72, 37, "LAFAYETTE, USA", 28, 6, 0, "28-6-0", "4", "2");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (52, "Beneil", "BAGEL", "Dariush", 155, 72, "1989-05-06", 32, 72, 36, "IRVINE, USA", 23, 4, 1, "23-4-1", "4", "3");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (53, "Tony", "EL CUCUY", "Ferguson", 155, 72, "1984-02-12", 37, 76, 38, "OXNARD, USA", 25, 6, 0, "25-6-0", "4", "4");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (54, "Islam", "MACH", "Makhachev", 155, 70, "1991-09-27", 31, 70, 34, "DAGESTAN, RUSSIA", 22, 1, 0, "22-1-0", "4", "5");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (55, "Conor", "THE NOTORIOUS", "McGregor", 155, 69, "1988-07-14", 33, 74, 38, "DUBLIN, IRELAND", 22, 6, 0, "22-6-0", "4", "6");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (56, "Rafael", "DOS ANJOS", "dos Anjos", 155, 69, "1984-10-26", 37, 70, 36, "RIO DE JANEIRO, BRAZIL", 30, 13, 0, "30-13-0", "4", "7");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (57, "Paul", "THE IRISH DRAGON", "Felder", 155, 70, "1985-04-25", 36, 71, 35, "PHILADELPHIA, USA", 18, 6, 0, "18-6-0", "4", "8");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (58, "Diego", "NIGHTMARE", "Sanchez", 155, 72, "1981-12-31", 41, 74, 37, "ALBUQUERQUE, USA", 30, 13, 0, "30-13-0", "4", "9");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (59, "Gregor", "THE GIFT", "Gillespie", 155, 69, "1987-07-29", 34, 70, 36, "ROCHESTER, USA", 14, 1, 0, "14-1-0", "4", "10");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (60, "Dan", "THE HANGMAN", "Hooker", 155, 75, "1989-02-13", 32, 75, 38, "AUCKLAND, NEW ZEALAND", 21, 11, 0, "21-11-0", "4", "11");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (61, "Carlos", "THE BULL", "Diego Ferreira", 155, 70, "1985-04-18", 36, 74, 38, "AMAZONAS, BRAZIL", 17, 4, 0, "17-4-0", "4", "12");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (62, "Al", "RAGING", "Iaquinta", 155, 69, "1987-04-30", 34, 70, 36, "NEW YORK, USA", 15, 6, 1, "15-6-1", "4", "13");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (63, "Nasrat", "THE AFGHAN", "Haqparast", 155, 70, "1995-09-22", 27, 72, 36, "HAMBURG, GERMANY", 14, 4, 0, "14-4-0", "4", "14");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (64, "Bobby", "KING", "Green", 155, 70, "1986-09-09", 35, 71, 37, "FONTANA, USA", 27, 12, 2, "27-12-2", "4", "15");

/* Peleadores de Welterweight */
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (65, "Kamaru", "THE NIGERIAN NIGHTMARE", "Usman", 170, 72, "1987-05-11", 36, 76, 38, "ABEOKUTA, NIGERIA", 19, 1, 0, "19-1-0", "5", "0");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (66, "Colby", "CHAOS", "Covington", 170, 72, "1988-02-22", 33, 72, 36, "DEERFIELD BEACH, USA", 16, 3, 0, "16-3-0", "5", "1");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (67, "Leon", "ROCKY", "Edwards", 170, 72, "1991-08-25", 30, 74, 36, "BIRMINGHAM, ENGLAND", 18, 3, 0, "18-3-0", "5", "2");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (68, "Gilbert", "DURINHO", "Burns", 170, 71, "1986-07-20", 35, 71, 38, "NITERÓI, BRAZIL", 20, 4, 0, "20-4-0", "5", "3");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (69, "Stephen", "WONDERBOY", "Thompson", 170, 73, "1983-02-11", 38, 75, 38, "SIMPSONVILLE, USA", 16, 5, 1, "16-5-1", "5", "4");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (70, "Michael", "THE MAVERICK", "Chiesa", 170, 75, "1987-12-07", 35, 77, 38, "SPOKANE, USA", 17, 5, 0, "17-5-0", "5", "5");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (71, "Nate", "THE STOCKTON SLAP", "Diaz", 170, 72, "1984-04-16", 37, 76, 38, "STOCKTON, USA", 20, 13, 0, "20-13-0", "5", "6");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (72, "Vicente", "THE SILENT ASSASSIN", "Luque", 170, 71, "1991-11-27", 30, 75, 38, "WESTWOOD, USA", 15, 7, 1, "15-7-1", "5", "7");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (73, "Geoff", "HANDS OF STEEL", "Neal", 170, 72, "1990-08-28", 31, 75, 38, "DALLAS, USA", 14, 4, 0, "14-4-0", "5", "8");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (74, "Robbie", "RUTHLESS", "Lawler", 170, 71, "1982-03-20", 39, 74, 38, "SAN DIEGO, USA", 28, 15, 0, "28-15-0", "5", "9");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (75, "Sean", "THE IRISH", "Brady", 170, 74, "1992-12-11", 29, 75, 38, "PHILADELPHIA, USA", 15, 0, 0, "15-0-0", "5", "10");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (76, "Neil", "2 TAP", "Magny", 170, 75, "1987-08-03", 34, 80, 38, "DENVER, USA", 25, 8, 0, "25-8-0", "5", "11");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (77, "Kevin", "THE MOTOWN PHENOM", "Lee", 170, 71, "1992-09-04", 29, 77, 38, "GRAND RAPIDS, USA", 18, 7, 0, "18-7-0", "5", "12");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (78, "Belal", "REMEMBER THE NAME", "Muhammad", 170, 71, "1988-07-09", 33, 75, 38, "CHICAGO, USA", 18, 3, 0, "18-3-0", "5", "13");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (79, "Jingliang", "THE LEECH", "Li", 170, 71, "1988-02-20", 33, 72, 38, "BAISHAN, CHINA", 18, 6, 0, "18-6-0", "5", "14");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (80, "Daniel", "D-Rod", "Rodriguez", 170, 72, "1987-07-29", 34, 74, 38, "ALBUQUERQUE, USA", 15, 2, 0, "15-2-0", "5", "15");

/* Peleadores de Middleweight */
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (81, "Israel", "THE LAST STYLEBENDER", "Adesanya", 185, 76, "1989-07-22", 32, 80, 44, "LAGOS, NIGERIA", 21, 1, 0, "21-1-0", "6", "0");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (82, "Robert", "THE REAPER", "Whittaker", 185, 72, "1990-12-20", 31, 73, 39, "SYDNEY, AUSTRALIA", 26, 5, 0, "26-5-0", "6", "1");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (83, "Jared", "THE KILLA GORILLA", "Cannonier", 185, 73, "1984-03-16", 37, 77, 43, "DALLAS, USA", 14, 5, 0, "14-5-0", "6", "2");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (84, "Marvin", "THE ITALIAN DREAM", "Vettori", 185, 72, "1993-09-20", 28, 74, 38, "MEZZOLOMBARDO, ITALY", 17, 5, 1, "17-5-1", "6", "3");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (85, "Derek", "THE GORILLA", "Brunson", 185, 74, "1984-01-04", 37, 77, 39, "WILMINGTON, USA", 23, 7, 0, "23-7-0", "6", "4");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (86, "Paulo", "THE ERASER", "Costa", 185, 73, "1991-04-21", 30, 72, 38, "BELO HORIZONTE, BRAZIL", 13, 1, 0, "13-1-0", "6", "5");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (87, "Uriah", "PRIME TIME", "Hall", 185, 74, "1984-07-31", 37, 79, 40, "KINGSTON, JAMAICA", 18, 9, 0, "18-9-0", "6", "6");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (88, "Sean", "TARZAN", "Strickland", 185, 75, "1990-02-27", 31, 76, 41, "ANAHEIM, USA", 25, 3, 0, "25-3-0", "6", "7");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (89, "Chris", "THE CRUSHER", "Weidman", 185, 74, "1984-06-17", 37, 78, 43, "BALDWIN, USA", 15, 6, 0, "15-6-0", "6", "8");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (90, "Jack", "THE HAMMER", "Hermansson", 185, 75, "1988-06-10", 33, 77, 40, "STOCKHOLM, SWEDEN", 22, 6, 0, "22-6-0", "6", "9");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (91, "Brad", "QUAKE", "Tavares", 185, 73, "1988-08-25", 33, 75, 39, "KAILUA, USA", 18, 6, 0, "18-6-0", "6", "10");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (92, "Edmen", "THE GOLDEN BOY", "Shahbazyan", 185, 74, "1997-11-20", 24, 74, 40, "GLENDALE, USA", 11, 2, 0, "11-2-0", "6", "11");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (93, "Brendan", "ALL IN", "Allen", 185, 74, "1996-03-28", 26, 74, 40, "KING'S LYNN, ENGLAND", 17, 4, 0, "17-4-0", "6", "12");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (94, "Sean", "THE SNIPER", "Brady", 185, 75, "1990-10-23", 31, 76, 40, "FEDERAL WAY, USA", 16, 0, 0, "16-0-0", "6", "13");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (95, "Omari", "WOLVERINE", "Akhmedov", 185, 73, "1987-05-12", 34, 75, 40, "MAKHACHKALA, RUSSIA", 21, 5, 1, "21-5-1", "6", "14");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (96, "Krzysztof", "THE POLISH EXPERIMENT", "Jotko", 185, 73, "1989-08-19", 32, 74, 39, "BYDGOSZCZ, POLAND", 23, 4, 0, "23-4-0", "6", "15");

/* Peleadores de Light heavyweight */
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (97, "Jan", "THE ERASER", "Błachowicz", 205, 74, "1983-02-24", 38, 78, 40, "CIESZYN, POLAND", 28, 8, 0, "28-8-0", "7", "0");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (98, "Glover", "THE LEGEND", "Teixeira", 205, 74, "1979-10-28", 42, 76, 40, "SOBREIRO CURUÇÁ, BRAZIL", 33, 7, 0, "33-7-0", "7", "1");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (99, "Alexander", "THE MAULER", "Gustafsson", 205, 76, "1987-01-15", 34, 79, 42, "ARBROATH, SWEDEN", 18, 7, 0, "18-7-0", "7", "2");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (100, "Thiago", "MARRETA", "Santos", 205, 73, "1983-01-07", 39, 76, 40, "RIO DE JANEIRO, BRAZIL", 22, 7, 0, "22-7-0", "7", "3");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (101, "Dominick", "THE DEVASTATOR", "Reyes", 205, 76, "1989-12-26", 32, 77, 43, "VICTORVILLE, USA", 14, 3, 0, "14-3-0", "7", "4");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (102, "Volkan", "NO TIME", "Oezdemir", 205, 75, "1989-08-19", 32, 75, 39, "FRIBOURG, SWITZERLAND", 18, 6, 0, "18-6-0", "7", "5");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (103, "Nikita", "THE MINER", "Krylov", 205, 75, "1992-03-07", 29, 77, 41, "DONETSK, UKRAINE", 27, 8, 0, "27-8-0", "7", "6");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (104, "Ryan", "SUPERMAN", "Spann", 205, 76, "1991-10-31", 30, 79, 44, "BEAUMONT, USA", 19, 7, 0, "19-7-0", "7", "7");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (105, "Magomed", "THE STOCKHOLM", "Ankalaev", 205, 76, "1992-04-02", 29, 77, 40, "MAKHACHKALA, RUSSIA", 15, 1, 0, "15-1-0", "7", "8");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (106, "Johnny", "BIG RIG", "Walker", 205, 76, "1992-03-20", 29, 77, 40, "RIO DE JANEIRO, BRAZIL", 18, 5, 0, "18-5-0", "7", "9");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (107, "Misha", "THE MENACE", "Cirkunov", 205, 74, "1986-02-27", 35, 75, 40, "DAUGAVPILS, LATVIA", 15, 6, 0, "15-6-0", "7", "10");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (108, "Ed", "SHORT FUSE", "Herman", 205, 74, "1980-12-02", 41, 73, 38, "PORTLAND, USA", 26, 14, 0, "26-14-0", "7", "11");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (109, "Michał", "LORD", "Oleksiejczuk", 205, 73, "1994-06-22", 27, 75, 42, "RADOM, POLAND", 15, 4, 0, "15-4-0", "7", "12");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (110, "Da Un", "EL TORNADO", "Jung", 205, 74, "1992-12-29", 29, 73, 39, "GYEONGSANGNAM-DO, SOUTH KOREA", 14, 2, 0, "14-2-0", "7", "13");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (111, "Mike", "SLOW", "Rodriguez", 205, 76, "1989-08-03", 32, 80, 45, "MILWAUKEE, USA", 12, 6, 0, "12-6-0", "7", "14");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (112, "Danilo", "MOTOMAN", "Marques", 205, 73, "1985-03-12", 36, 76, 40, "ITAGUAÍ, BRAZIL", 11, 3, 0, "11-3-0", "7", "15");

/* Peleadores de Heavyweight */
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (113, "Francis", "THE PREDATOR", "Ngannou", 265, 76, "1986-09-05", 36, 83, 44, "BATIE, CAMEROON", 16, 3, 0, "16-3-0", "8", "0");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (114, "Ciryl", "BON GAMIN", "Gane", 265, 79, "1990-04-12", 31, 81, 42, "LA ROCHELLE, FRANCE", 10, 0, 0, "10-0-0", "8", "1");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (115, "Stipe", "STONE COLD", "Miocic", 265, 76, "1982-08-19", 39, 80, 41, "EUCLID, USA", 21, 4, 0, "21-4-0", "8", "2");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (116, "Jon", "BONES", "Jones", 265, 76, "1987-07-19", 34, 84, 45, "ROCHESTER, USA", 26, 1, 0, "26-1-0", "8", "3");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (117, "Derrick", "THE BLACK BEAST", "Lewis", 265, 75, "1985-02-07", 37, 79, 42, "NEW ORLEANS, USA", 25, 7, 0, "25-7-0", "8", "4");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (118, "Alistair", "THE REEM", "Overeem", 265, 77, "1980-05-17", 41, 80, 43, "HOUNSLOW, ENGLAND", 47, 19, 0, "47-19-0", "8", "5");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (119, "Curtis", "RAZOR", "Blaydes", 265, 76, "1991-02-18", 30, 80, 44, "NAPERVILLE, USA", 15, 3, 0, "15-3-0", "8", "6");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (120, "Tai", "BAMBAM", "Tuivasa", 265, 74, "1993-03-16", 28, 75, 39, "SYDNEY, AUSTRALIA", 12, 3, 0, "12-3-0", "8", "7");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (121, "Blagoy", "BAGATA", "Ivanov", 265, 72, "1986-10-09", 34, 73, 38, "SOFIA, BULGARIA", 19, 4, 0, "19-4-0", "8", "8");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (122, "Shamil", "ABREK", "Abdurakhimov", 265, 75, "1981-09-02", 39, 76, 41, "DALNEKEYEVO, RUSSIA", 20, 6, 0, "20-6-0", "8", "9");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (123, "Serghei", "PANIC", "Spivac", 265, 75, "1995-01-29", 26, 78, 40, "MUNCI-NEGRENI, MOLDOVA", 13, 2, 0, "13-2-0", "8", "10");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (124, "Alexey", "THE BOA CONSTRICTOR", "Oleynik", 265, 74, "1977-06-25", 44, 80, 45, "KHARKOV, UKRAINE", 59, 15, 1, "59-15-1", "8", "11");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (125, "Marcin", "TYBUR", "Tybura", 265, 75, "1985-11-09", 36, 78, 41, "UNIÓW, POLAND", 23, 7, 0, "23-7-0", "8", "12");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (126, "Augusto", "SAKAI", "Sakai", 265, 76, "1991-07-19", 30, 77, 43, "CURITIBA, BRAZIL", 16, 2, 1, "16-2-1", "8", "13");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (127, "Tom", "THE TANK", "Aspinall", 265, 76, "1993-05-01", 28, 75, 40, "WIGAN, ENGLAND", 12, 2, 0, "12-2-0", "8", "14");
INSERT INTO ufc.fighter (id, name, nickname, surname, weight, height, date_of_birth, age, reach, leg_reach, nationality, win_fights, lost_fights, draw_fights, record, ranking_id, ranking_number) VALUES (128, "Alex", "THE GREAT", "Lungu", 265, 72, "1974-08-26", 47, 78, 40, "BUCHAREST, ROMANIA", 12, 4, 0, "12-4-0", "8", "15");

/* Evento */

INSERT INTO ufc.event (id, fight_date, event_number, information, place, title) VALUES (1, "2023-10-06T01:00:00", "UFC 293", "ESTO ES UNA PRUEBA DE EVENTO", "MADRID", "PELEADOR 1 VS PELEADOR 2");

/* Peleas */
INSERT INTO ufc.fight (id, event_id, company, title) VALUES (1,1, "UFC", "PRUEBA 1 VS PRUEBA 2");
INSERT INTO ufc.fight_fighter(fight_id, fighter_id) VALUES (1,1);
INSERT INTO ufc.fight_fighter(fight_id, fighter_id) VALUES (1,2);